### ISSUE TITLE
NullPointerException in SettingsActivity

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/SafeSlinger-Android#101]
1.8.2 Google Play:
java.lang.RuntimeException: Unable to start activity ComponentInfo{edu.cmu.cylab.starslinger/edu.cmu.cylab.starslinger.view.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.setSummary(java.lang.CharSequence)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.setSummary(java.lang.CharSequence)' on a null object reference
at edu.cmu.cylab.starslinger.view.SettingsActivity.setContactPushToken(SettingsActivity.java:498)
at edu.cmu.cylab.starslinger.view.SettingsActivity.setMessagePreferences(SettingsActivity.java:175)
at edu.cmu.cylab.starslinger.view.SettingsActivity.setPrefs(SettingsActivity.java:154)
at edu.cmu.cylab.starslinger.view.SettingsActivity.onCreate(SettingsActivity.java:120)
at android.app.Activity.performCreate(Activity.java:5933)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
... 10 more

**Comment by SafeSlingerProject** [comment]
Android 5.0
Related: Mu, Check ~ the "SafeSlinger" the latest version dies at # Settings dialog transition "in the F-02G!
