### ISSUE TITLE
NullPointerException in DraftData

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-Android#106]
Found during testing. Attempt to send draft message when server returns an 'Error='

FATAL EXCEPTION: AsyncTask #2
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
at edu.cmu.cylab.starslinger.model.DraftData.getRecipRowId(DraftData.java:104)
at edu.cmu.cylab.starslinger.view.HomeActivity$SendMessageTask.doInBackground(HomeActivity.java:3429)
at edu.cmu.cylab.starslinger.view.HomeActivity$SendMessageTask.doInBackground(HomeActivity.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
... 4 more

**Comment by mwfarb** [comment]
A few cascade results from this:
- InvalidRegistration is returned sending in Messages tab causes crash, no inactive_reg_date set (must fix).
- InvalidRegistration is returned sending in Compose tab no crash, yes inactive_reg_date set (OK).
- Reply is now disabled in Messages tab (OK). 
- Using Compose tab to send message succeeds is registration becomes active again but does not remove the inactive_reg_date such that reply will work again (must fix).

**Comment by mwfarb** [comment]
Closed with migration to GCM. Play services required now. Send-only mode is no longer possible.
