### ISSUE TITLE
NullPointerException in BaseActivity

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-Android#107]
Google Play for 1.8.2.1
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] edu.cmu.cylab.starslinger.view.BaseActivity.getContactPhoto(java.lang.String)' on a null object reference
at edu.cmu.cylab.starslinger.view.ComposeFragment$6.run(ComposeFragment.java:248)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5633)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

**Comment by mwfarb** [comment]
Now checking Activity exists first in this race condition.
