### ISSUE TITLE
IllegalStateException in RecipientDbAdapter

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-Android#110]
Google Play 1.8.2.1:
java.lang.RuntimeException: Unable to start service edu.cmu.cylab.starslinger.Service@42a920f8 with Intent { cmp=edu.cmu.cylab.starslinger/.Service }: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/edu.cmu.cylab.starslinger/databases/safeslinger.recipient
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3007)
at android.app.ActivityThread.access$2200(ActivityThread.java:170)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5635)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/edu.cmu.cylab.starslinger/databases/safeslinger.recipient
at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1277)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1153)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1321)
at edu.cmu.cylab.starslinger.model.RecipientDbAdapter.query(RecipientDbAdapter.java:179)
at edu.cmu.cylab.starslinger.model.RecipientDbAdapter.getTrustedRecipientCount(RecipientDbAdapter.java:742)
at edu.cmu.cylab.starslinger.Service.queryExchangeStatus(Service.java:212)
at edu.cmu.cylab.starslinger.Service.onStart(Service.java:147)
at android.app.Service.onStartCommand(Service.java:450)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2990)
... 10 more

**Comment by hasitpbhatt** [comment]
Please check the commit, and merge it.

**Comment by SafeSlingerProject** [comment]
It doesn't compile.

**Comment by SafeSlingerProject** [comment]
still an issue...

version 1.8.4
Galaxy Note4 (trltetmo)
Android 5.0
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/edu.cmu.cylab.starslinger/databases/safeslinger.recipient2
at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1282)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1158)
at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1326)
at edu.cmu.cylab.starslinger.model.RecipientDbAdapter.query(RecipientDbAdapter.java:191)
at edu.cmu.cylab.starslinger.model.RecipientDbAdapter.fetchAllPublicKeys(RecipientDbAdapter.java:621)
at edu.cmu.cylab.starslinger.view.BaseActivity.doUpdateRecipientsFromContacts(BaseActivity.java:1051)
at edu.cmu.cylab.starslinger.view.BaseActivity.access$000(BaseActivity.java:113)
at edu.cmu.cylab.starslinger.view.BaseActivity$BackgroundSyncUpdatesTask.doInBackground(BaseActivity.java:914)
at edu.cmu.cylab.starslinger.view.BaseActivity$BackgroundSyncUpdatesTask.doInBackground(BaseActivity.java:908)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
