### ISSUE TITLE
NetworkOnMainThreadException

### ISSUE THREAD

**Issue by Valodim** [SafeSlingerProject/SafeSlinger-Android#133]
```
java.lang.RuntimeException: Unable to destroy activity {org.sufficientlysecure.keychain/edu.cmu.cylab.starslinger.exchange.ExchangeActivity}: android.os.NetworkOnMainThreadException
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3521)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3539)
at android.app.ActivityThread.access$1400(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5146)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.NetworkOnMainThreadException
at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1010)
at org.apache.http.impl.SocketHttpClientConnection.close(SocketHttpClientConnection.java:205)
at org.apache.http.impl.conn.DefaultClientConnection.close(DefaultClientConnection.java:161)
at org.apache.http.impl.conn.tsccm.AbstractConnPool.closeConnection(AbstractConnPool.java:320)
at org.apache.http.impl.conn.tsccm.ConnPoolByRoute.shutdown(ConnPoolByRoute.java:678)
at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.shutdown(ThreadSafeClientConnManager.java:256)
at edu.cmu.cylab.starslinger.exchange.WebEngine.shutdownConnection(WebEngine.java:138)
at edu.cmu.cylab.starslinger.exchange.ExchangeController.endProtocol(ExchangeController.java:1126)
at edu.cmu.cylab.starslinger.exchange.ExchangeActivity.onDestroy(ExchangeActivity.java:787)
```

getting (rare) reports of this in our developer console

**Comment by mwfarb** [comment]
Hey @Valodim! I think we need to get you the latest stable commit of the library. I believe we closed this one in https://github.com/SafeSlingerProject/SafeSlinger-Android/issues/100 with https://github.com/SafeSlingerProject/SafeSlinger-Android/commit/95bb2c4fc250e8d1112c955bdc4baf9dd00a5427.

But for the exchange library used in OKC I'd pull this commit in: https://github.com/SafeSlingerProject/exchange-android/commit/9c1674e972df19b9bd1900db657ddbaf8c1acb29, which will have that fix plus a number of other minor updates.

**Comment by mwfarb** [comment]
I believe we closed this one in https://github.com/SafeSlingerProject/SafeSlinger-Android/issues/100 with https://github.com/SafeSlingerProject/SafeSlinger-Android/commit/95bb2c4fc250e8d1112c955bdc4baf9dd00a5427.

For the integration repo, I'd use https://github.com/SafeSlingerProject/exchange-android/commit/9c1674e972df19b9bd1900db657ddbaf8c1acb29, which will have that fix and a number of smaller updates we're using in production.

**Comment by mwfarb** [comment]
Nothing like thinking github ate your comment, rewriting it, then finding it was posted all along.

**Comment by Valodim** [comment]
Oh, great! Will include ASAP. Thanks for your work! :+1:
